DROP TABLE IF EXISTS login CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS ubicaciones CASCADE;
DROP TABLE IF EXISTS prioridades CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS incidencias CASCADE;
DROP TABLE IF EXISTS asignaciones CASCADE;
DROP TABLE IF EXISTS comentarios CASCADE;
DROP TABLE IF EXISTS historialincidencias CASCADE;
DROP TABLE IF EXISTS adjuntos CASCADE;

CREATE TABLE login (
    id_login INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo_login VARCHAR(100) NOT NULL UNIQUE,
    usuario_login VARCHAR(50) NOT NULL UNIQUE,
    contrasena_login VARCHAR(100) NOT NULL,
    rol_login VARCHAR(30) NOT NULL CHECK (rol_login IN ('Administrador','Profesor','Personal TICS','Personal Servicios','Personal Infraestructura')),
    estado_login SMALLINT DEFAULT 1 CHECK (estado_login IN (0,1))
);

CREATE TABLE departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado_departamento SMALLINT DEFAULT 1 CHECK (estado_departamento IN (0,1))
);

CREATE TABLE ubicaciones (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ubicacion VARCHAR(100) NOT NULL,
    nivel VARCHAR(30),
    descripcion TEXT,
    estado_ubicacion SMALLINT DEFAULT 1 CHECK (estado_ubicacion IN (0,1))
);

CREATE TABLE prioridades (
    id_prioridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_prioridad VARCHAR(20) NOT NULL UNIQUE CHECK (nombre_prioridad IN ('Baja','Media','Alta','Critica')),
    descripcion TEXT,
    estado_prioridad SMALLINT DEFAULT 1 CHECK (estado_prioridad IN (0,1))
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_login INTEGER,
    id_departamento INTEGER,
    nombre_usuario VARCHAR(50) NOT NULL,
    apellido_usuario VARCHAR(50) NOT NULL,
    telefono VARCHAR(15),
    estado_usuario SMALLINT DEFAULT 1 CHECK (estado_usuario IN (0,1)),
    CONSTRAINT fk_usuario_login FOREIGN KEY (id_login) REFERENCES login(id_login) ON DELETE SET NULL,
    CONSTRAINT fk_usuario_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE SET NULL
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL,
    nombre_categoria VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado_categoria SMALLINT DEFAULT 1 CHECK (estado_categoria IN (0,1)),
    CONSTRAINT fk_categoria_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE CASCADE
);

CREATE TABLE incidencias (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    id_prioridad INTEGER NOT NULL,
    titulo_incidencia VARCHAR(100) NOT NULL,
    descripcion_incidencia TEXT NOT NULL,
    estado_incidencia VARCHAR(30) DEFAULT 'Pendiente' CHECK (estado_incidencia IN ('Pendiente','En Revision','En Proceso','Resuelto','Cerrado')),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_resolucion TIMESTAMP,
    CONSTRAINT fk_incidencia_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones(id_ubicacion) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_prioridad FOREIGN KEY (id_prioridad) REFERENCES prioridades(id_prioridad) ON DELETE CASCADE
);

CREATE TABLE asignaciones (
    id_asignacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMP,
    observaciones TEXT,
    estado_asignacion SMALLINT DEFAULT 1 CHECK (estado_asignacion IN (0,1)),
    CONSTRAINT fk_asignacion_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_asignacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    comentario TEXT NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentario_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE historialincidencias (
    id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo VARCHAR(30) NOT NULL,
    comentario TEXT,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historial_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE adjuntos (
    id_adjunto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    nombre_archivo VARCHAR(100) NOT NULL,
    ruta_archivo VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(50),
    fecha_archivo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adjunto_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_adjunto_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- Datos de login
INSERT INTO login VALUES (1,'admin.general@cartagena.edu','admin_gral','pass1234','Administrador',1),(2,'tics.soporte1@cartagena.edu','tics_juan','pass1234','Personal TICS',1),(3,'tics.soporte2@cartagena.edu','tics_maria','pass1234','Personal TICS',1),(4,'prof.matematicas@cartagena.edu','prof_carlos','pass1234','Profesor',1),(5,'prof.historia@cartagena.edu','prof_ana','pass1234','Profesor',1),(6,'servicios.limpieza@cartagena.edu','serv_pedro','pass1234','Personal Servicios',1),(7,'servicios.mantenimiento@cartagena.edu','serv_luisa','pass1234','Personal Servicios',1),(8,'infra.redes@cartagena.edu','infra_jorge','pass1234','Personal Infraestructura',1),(9,'prof.ciencias@cartagena.edu','prof_sofia','pass1234','Profesor',1),(10,'infra.seguridad@cartagena.edu','infra_carmen','pass1234','Personal Infraestructura',1);

-- Datos de departamentos
INSERT INTO departamentos VALUES (1,'Dirección General','Departamento administrativo y de dirección superior',1),(2,'Soporte TICS','Soporte técnico, equipos de cómputo y software institucional',1),(3,'Infraestructura y Redes','Mantenimiento de redes, cableado y servidores',1),(4,'Servicios Generales','Limpieza, conserjería y áreas comunes',1),(5,'Académico - Matemáticas','Departamento de enseñanza de matemáticas y física',1),(6,'Académico - Ciencias','Laboratorios y materias científicas',1),(7,'Académico - Humanidades','Historia, literatura y ciencias sociales',1),(8,'Mantenimiento Fiduciario','Reparaciones locativas, plomería y electricidad',1),(9,'Recursos Humanos','Gestión de personal docente y administrativo',1),(10,'Biblioteca','Gestión de libros, salas de lectura y recursos digitales',1);

-- Datos de ubicaciones
INSERT INTO ubicaciones VALUES (1,'Edificio A - Aula 101','Nivel 1','Salón de clases principal planta baja',1),(2,'Edificio A - Aula 202','Nivel 2','Salón de clases planta alta',1),(3,'Edificio B - Laboratorio de Computación','Nivel 1','Sala de equipos y prácticas TICS',1),(4,'Edificio B - Laboratorio de Ciencias','Nivel 2','Laboratorio de física y química',1),(5,'Biblioteca Central','Nivel 1','Área de lectura y estanterías',1),(6,'Oficinas Administrativas','Nivel 1','Dirección y secretaría general',1),(7,'Salón de Profesores','Nivel 2','Área de descanso y planeación docente',1),(8,'Área Deportiva - Gimnasio','Nivel 1','Gimnasio techado institucional',1),(9,'Cafetería Estudiantil','Nivel 1','Área de comidas y descanso',1),(10,'Centro de Servidores (DataCenter)','Nivel 1','Cuarto técnico de redes principal',1);

-- Datos de prioridades
INSERT INTO prioridades VALUES (1,'Baja','Incidencias menores que no afectan la operatividad inmediata',1),(2,'Media','Incidencias que afectan parcialmente las labores cotidianas',1),(3,'Alta','Problemas urgentes que detienen una actividad importante',1),(4,'Critica','Emergencias absolutas que paralizan áreas completas o sistemas',1);

-- Datos de usuarios
INSERT INTO usuarios VALUES (1,1,1,'Roberto','Mendoza','5551-0101',1),(2,2,2,'Juan','Pérez','5551-0202',1),(3,3,2,'María','Gómez','5551-0303',1),(4,4,5,'Carlos','López','5551-0404',1),(5,5,7,'Ana','Martínez','5551-0505',1),(6,6,4,'Pedro','Sánchez','5551-0606',1),(7,7,8,'Luisa','Fernández','5551-0707',1),(8,8,3,'Jorge','Ramírez','5551-0808',1),(9,9,6,'Sofía','Castillo','5551-0909',1),(10,10,8,'Carmen','Morales','5551-1010',1);

-- Datos de categorias
INSERT INTO categorias VALUES (1,2,'Fallos de Hardware','Problemas con computadoras, pantallas o proyectores',1),(2,2,'Problemas de Software','Errores en sistemas operativos o aplicaciones institucionales',1),(3,3,'Conectividad Wi-Fi','Fallas en la señal inalámbrica del campus',1),(4,3,'Cables de Red','Puntos de red dañados o sin conexión física',1),(5,4,'Limpieza de Aula','Solicitud de limpieza en salones específicos',1),(6,8,'Iluminación','Bombillas fundidas o problemas con interruptores',1),(7,8,'Plomería y Fugas','Problemas en tuberías, baños o bebederos',1),(8,5,'Material Didáctico','Falta de recursos en aulas de matemáticas',1),(9,6,'Equipos de Laboratorio','Mal funcionamiento de microscopios o instrumentos',1),(10,10,'Préstamo de Libros','Incidencias con el catálogo o sistema de biblioteca',1);

-- Datos de incidencias
INSERT INTO incidencias VALUES (1,4,1,1,2,'Proyector sin video','El proyector del aula 101 no enciende al conectar la laptop','Pendiente','2026-09-08 19:38:02',NULL),(2,5,2,2,3,'Error en plataforma virtual','No carga el módulo de calificaciones para el curso de historia','Pendiente','2026-09-08 19:38:02',NULL),(3,4,3,3,2,'Sin señal de Wi-Fi en lab','Los equipos de computación no detectan la red institucional','Pendiente','2026-09-08 19:38:02',NULL),(4,6,5,9,1,'Basura acumulada en cafetería','Se requiere recolección urgente de residuos en mesas exteriores','Pendiente','2026-09-08 19:38:02',NULL),(5,7,6,7,2,'Lámpara fundida','La iluminación del salón de profesores parpadea constantemente','Pendiente','2026-09-08 19:38:02',NULL),(6,8,4,10,4,'Caída del servidor principal','Inaccesibilidad total a los sistemas de red y carpetas compartidas','Pendiente','2026-09-08 19:38:02',NULL),(7,9,9,4,3,'Microscopio dañado','El lente del microscopio número 4 está rayado','Pendiente','2026-09-08 19:38:02',NULL),(8,4,8,1,1,'Pintura descascarada','Se observa daño estético en la pared lateral del aula 101','Pendiente','2026-09-08 19:38:02',NULL),(9,5,7,5,3,'Fuga de agua en baños','Grifo roto en el baño principal de la biblioteca','Pendiente','2026-09-08 19:38:02',NULL),(10,10,10,5,2,'Sistema de biblioteca lento','El software de búsqueda de libros presenta retrasos','Pendiente','2026-09-08 19:38:02',NULL);

-- Datos de asignaciones
INSERT INTO asignaciones VALUES (1,1,2,'2026-09-08 19:38:02',NULL,'Asignado a revisión técnica de proyector',1),(2,2,3,'2026-09-08 19:38:02',NULL,'Revisión de base de datos y credenciales de usuario',1),(3,3,8,'2026-09-08 19:38:02',NULL,'Inspección del Access Point del edificio B',1),(4,4,6,'2026-09-08 19:38:02',NULL,'Turno de limpieza asignado al personal de servicio',1),(5,5,7,'2026-09-08 19:38:02',NULL,'Cambio de balastro y bombilla programado',1),(6,6,8,'2026-09-08 19:38:02',NULL,'Atención inmediata por caída de servidores',1),(7,7,3,'2026-09-08 19:38:02',NULL,'Revisión de equipo especializado de laboratorio',1),(8,8,7,'2026-09-08 19:38:02',NULL,'Evaluación de daños estéticos',1),(9,9,7,'2026-09-08 19:38:02',NULL,'Reparación de tubería y grifería',1),(10,10,2,'2026-09-08 19:38:02',NULL,'Optimización de base de datos bibliotecaria',1);

-- Datos de comentarios
INSERT INTO comentarios VALUES (1,1,4,'El cable VGA ya fue probado pero el puerto no responde.','2026-09-08 19:38:02'),(2,2,5,'Aún no puedo acceder con mi usuario institucional.','2026-09-08 19:38:02'),(3,3,2,'El punto de red ya da enlace intermitente.','2026-09-08 19:38:02'),(4,4,6,'Área limpia y despejada.','2026-09-08 19:38:02'),(5,5,7,'La iluminación quedó funcionando correctamente.','2026-09-08 19:38:02'),(6,6,8,'Servicios restaurados al 100%.','2026-09-08 19:38:02'),(7,7,9,'Se necesita cotizar repuesto con proveedor externo.','2026-09-08 19:38:02'),(8,8,4,'Esperando aprobación para iniciar trabajos de pintura.','2026-09-08 19:38:02'),(9,9,7,'Fuga controlada exitosamente.','2026-09-08 19:38:02'),(10,10,10,'El sistema responde mucho más rápido ahora.','2026-09-08 19:38:02');

-- Datos de historialincidencias
INSERT INTO historialincidencias VALUES (1,1,2,'Pendiente','En Revision','Se recibe la incidencia y se verifica el equipo.','2026-09-08 19:38:02'),(2,2,3,'Pendiente','En Proceso','Se contacta al proveedor del software.','2026-09-08 19:38:02'),(3,3,8,'Pendiente','En Revision','Verificando estado del router principal.','2026-09-08 19:38:02'),(4,4,6,'Pendiente','En Proceso','Personal de limpieza enviado al área.','2026-09-08 19:38:02'),(5,5,7,'Pendiente','Resuelto','Lámpara sustituida con éxito.','2026-09-08 19:38:02'),(6,6,8,'Pendiente','Critica / En Proceso','Reinicio forzoso de servidores y respaldo.','2026-09-08 19:38:02'),(7,7,3,'Pendiente','En Revision','Revisando inventario de repuestos.','2026-09-08 19:38:02'),(8,8,7,'Pendiente','Pendiente','A la espera de presupuesto para pintura.','2026-09-08 19:38:02'),(9,9,7,'Pendiente','En Proceso','Cerrada llave de paso principal para reparación.','2026-09-08 19:38:02'),(10,10,2,'Pendiente','Resuelto','Servidor de biblioteca optimizado.','2026-09-08 19:38:02');

-- Datos de adjuntos
INSERT INTO adjuntos VALUES (1,1,4,'error_proyector.png','/uploads/incidencias/error_proyector.png','image/png','2026-09-08 19:38:02'),(2,2,5,'captura_error_login.jpg','/uploads/incidencias/captura_error_login.jpg','image/jpeg','2026-09-08 19:38:02'),(3,3,4,'test_ping.log','/uploads/incidencias/test_ping.log','text/plain','2026-09-08 19:38:02'),(4,4,6,'estado_cafeteria.jpg','/uploads/incidencias/estado_cafeteria.jpg','image/jpeg','2026-09-08 19:38:02'),(5,5,7,'lampara_rota.jpg','/uploads/incidencias/lampara_rota.jpg','image/jpeg','2026-09-08 19:38:02'),(6,6,8,'log_servidor.txt','/uploads/incidencias/log_servidor.txt','text/plain','2026-09-08 19:38:02'),(7,7,9,'microscopio_daño.png','/uploads/incidencias/microscopio_dano.png','image/png','2026-09-08 19:38:02'),(8,8,4,'pared_aula101.jpg','/uploads/incidencias/pared_aula101.jpg','image/jpeg','2026-09-08 19:38:02'),(9,9,7,'fuga_bano.mp4','/uploads/incidencias/fuga_bano.mp4','video/mp4','2026-09-08 19:38:02'),(10,10,10,'reporte_rendimiento.pdf','/uploads/incidencias/reporte_rendimiento.pdf','application/pdf','2026-09-08 19:38:02');

SELECT setval(pg_get_serial_sequence('login', 'id_login'), COALESCE((SELECT MAX(id_login) FROM login), 1), true);
SELECT setval(pg_get_serial_sequence('departamentos', 'id_departamento'), COALESCE((SELECT MAX(id_departamento) FROM departamentos), 1), true);
SELECT setval(pg_get_serial_sequence('ubicaciones', 'id_ubicacion'), COALESCE((SELECT MAX(id_ubicacion) FROM ubicaciones), 1), true);
SELECT setval(pg_get_serial_sequence('prioridades', 'id_prioridad'), COALESCE((SELECT MAX(id_prioridad) FROM prioridades), 1), true);
SELECT setval(pg_get_serial_sequence('usuarios', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM usuarios), 1), true);
SELECT setval(pg_get_serial_sequence('categorias', 'id_categoria'), COALESCE((SELECT MAX(id_categoria) FROM categorias), 1), true);
SELECT setval(pg_get_serial_sequence('incidencias', 'id_incidencia'), COALESCE((SELECT MAX(id_incidencia) FROM incidencias), 1), true);
SELECT setval(pg_get_serial_sequence('asignaciones', 'id_asignacion'), COALESCE((SELECT MAX(id_asignacion) FROM asignaciones), 1), true);
SELECT setval(pg_get_serial_sequence('comentarios', 'id_comentario'), COALESCE((SELECT MAX(id_comentario) FROM comentarios), 1), true);
SELECT setval(pg_get_serial_sequence('historialincidencias', 'id_historial'), COALESCE((SELECT MAX(id_historial) FROM historialincidencias), 1), true);
SELECT setval(pg_get_serial_sequence('adjuntos', 'id_adjunto'), COALESCE((SELECT MAX(id_adjunto) FROM adjuntos), 1), true);
CREATE OR REPLACE PROCEDURE public.sp_actualizaradjunto(p_id int, p_id_incidencia int, p_id_usuario int, p_nombre_archivo VARCHAR(100), p_ruta_archivo VARCHAR(255), p_tipo_archivo VARCHAR(50))
LANGUAGE plpgsql
AS $$
BEGIN
    update adjuntos
        set id_incidencia = p_id_incidencia,
            id_usuario = p_id_usuario,
            nombre_archivo = p_nombre_archivo,
            ruta_archivo = p_ruta_archivo,
            tipo_archivo = p_tipo_archivo
        where id_adjunto = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarasignacion(p_id int, p_id_incidencia int, p_id_usuario int, p_fecha_finalizacion timestamp, p_observaciones text, p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update asignaciones
        set id_incidencia = p_id_incidencia,
            id_usuario = p_id_usuario,
            fecha_finalizacion = p_fecha_finalizacion,
            observaciones = p_observaciones,
            estado_asignacion = p_estado::smallint
        where id_asignacion = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarcategoria(p_id int, p_id_departamento int, p_nombre VARCHAR(80), p_descripcion text, p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update categorias
        set id_departamento = p_id_departamento,
            nombre_categoria = p_nombre,
            descripcion = p_descripcion,
            estado_categoria = p_estado::smallint
        where id_categoria = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarcomentario(p_id int, p_id_incidencia int, p_id_usuario int, p_comentario text)
LANGUAGE plpgsql
AS $$
BEGIN
    update comentarios
        set id_incidencia = p_id_incidencia,
            id_usuario = p_id_usuario,
            comentario = p_comentario
        where id_comentario = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizardepartamento(p_id int, p_nombre VARCHAR(80), p_descripcion text, p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update departamentos
        set nombre_departamento = p_nombre,
            descripcion = p_descripcion,
            estado_departamento = p_estado::smallint
        where id_departamento = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarhistorial(p_id int, p_id_incidencia int, p_id_usuario int, p_estado_anterior VARCHAR(30), p_estado_nuevo VARCHAR(30), p_comentario text)
LANGUAGE plpgsql
AS $$
BEGIN
    update historialincidencias
        set id_incidencia = p_id_incidencia,
            id_usuario = p_id_usuario,
            estado_anterior = p_estado_anterior,
            estado_nuevo = p_estado_nuevo,
            comentario = p_comentario
        where id_historial = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarincidencia(p_id int, p_id_usuario int, p_id_categoria int, p_id_ubicacion int, p_id_prioridad int, p_titulo VARCHAR(100), p_descripcion text, p_estado VARCHAR(30), p_fecha_resolucion timestamp)
LANGUAGE plpgsql
AS $$
BEGIN
    update incidencias
        set id_usuario = p_id_usuario,
            id_categoria = p_id_categoria,
            id_ubicacion = p_id_ubicacion,
            id_prioridad = p_id_prioridad,
            titulo_incidencia = p_titulo,
            descripcion_incidencia = p_descripcion,
            estado_incidencia = p_estado,
            fecha_resolucion = p_fecha_resolucion
        where id_incidencia = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarlogin(p_id int, p_correo VARCHAR(100), p_usuario VARCHAR(50), p_contrasena VARCHAR(100), p_rol VARCHAR(30), p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update login
        set correo_login = p_correo,
            usuario_login = p_usuario,
            contrasena_login = p_contrasena,
            rol_login = p_rol,
            estado_login = p_estado::smallint
        where id_login = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarprioridad(p_id int, p_nombre VARCHAR(20), p_descripcion text, p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update prioridades
        set nombre_prioridad = p_nombre,
            descripcion = p_descripcion,
            estado_prioridad = p_estado::smallint
        where id_prioridad = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarubicacion(p_id int, p_nombre VARCHAR(100), p_nivel VARCHAR(30), p_descripcion text, p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update ubicaciones
        set nombre_ubicacion = p_nombre,
            nivel = p_nivel,
            descripcion = p_descripcion,
            estado_ubicacion = p_estado::smallint
        where id_ubicacion = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_actualizarusuario(p_id int, p_id_login int, p_id_departamento int, p_nombre VARCHAR(50), p_apellido VARCHAR(50), p_telefono VARCHAR(15), p_estado boolean)
LANGUAGE plpgsql
AS $$
BEGIN
    update usuarios
        set id_login = p_id_login,
            id_departamento = p_id_departamento,
            nombre_usuario = p_nombre,
            apellido_usuario = p_apellido,
            telefono = p_telefono,
            estado_usuario = p_estado::smallint
        where id_usuario = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregaradjunto(p_id_incidencia int, p_id_usuario int, p_nombre_archivo VARCHAR(100), p_ruta_archivo VARCHAR(255), p_tipo_archivo VARCHAR(50))
LANGUAGE plpgsql
AS $$
BEGIN
    insert into adjuntos (
            id_incidencia,
            id_usuario,
            nombre_archivo,
            ruta_archivo,
            tipo_archivo
        )
        values (
            p_id_incidencia,
            p_id_usuario,
            p_nombre_archivo,
            p_ruta_archivo,
            p_tipo_archivo
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarasignacion(p_id_incidencia int, p_id_usuario int, p_observaciones text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into asignaciones (
            id_incidencia,
            id_usuario,
            observaciones
        )
        values (
            p_id_incidencia,
            p_id_usuario,
            p_observaciones
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarcategoria(p_id_departamento int, p_nombre VARCHAR(80), p_descripcion text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into categorias (
            id_departamento,
            nombre_categoria,
            descripcion
        )
        values (
            p_id_departamento,
            p_nombre,
            p_descripcion
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarcomentario(p_id_incidencia int, p_id_usuario int, p_comentario text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into comentarios (
            id_incidencia,
            id_usuario,
            comentario
        )
        values (
            p_id_incidencia,
            p_id_usuario,
            p_comentario
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregardepartamento(p_nombre VARCHAR(80), p_descripcion text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into departamentos (
            nombre_departamento,
            descripcion
        )
        values (
            p_nombre,
            p_descripcion
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarhistorial(p_id_incidencia int, p_id_usuario int, p_estado_anterior VARCHAR(30), p_estado_nuevo VARCHAR(30), p_comentario text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into historialincidencias (
            id_incidencia,
            id_usuario,
            estado_anterior,
            estado_nuevo,
            comentario
        )
        values (
            p_id_incidencia,
            p_id_usuario,
            p_estado_anterior,
            p_estado_nuevo,
            p_comentario
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarincidencia(p_id_usuario int, p_id_categoria int, p_id_ubicacion int, p_id_prioridad int, p_titulo VARCHAR(100), p_descripcion text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into incidencias (
            id_usuario,
            id_categoria,
            id_ubicacion,
            id_prioridad,
            titulo_incidencia,
            descripcion_incidencia
        )
        values (
            p_id_usuario,
            p_id_categoria,
            p_id_ubicacion,
            p_id_prioridad,
            p_titulo,
            p_descripcion
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarlogin(p_correo VARCHAR(100), p_usuario VARCHAR(50), p_contrasena VARCHAR(100), p_rol VARCHAR(30))
LANGUAGE plpgsql
AS $$
BEGIN
    insert into login (
            correo_login,
            usuario_login,
            contrasena_login,
            rol_login
        )
        values (
            p_correo,
            p_usuario,
            p_contrasena,
            p_rol
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarprioridad(p_nombre VARCHAR(20), p_descripcion text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into prioridades (
            nombre_prioridad,
            descripcion
        )
        values (
            p_nombre,
            p_descripcion
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarubicacion(p_nombre VARCHAR(100), p_nivel VARCHAR(30), p_descripcion text)
LANGUAGE plpgsql
AS $$
BEGIN
    insert into ubicaciones (
            nombre_ubicacion,
            nivel,
            descripcion
        )
        values (
            p_nombre,
            p_nivel,
            p_descripcion
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_agregarusuario(p_id_login int, p_id_departamento int, p_nombre VARCHAR(50), p_apellido VARCHAR(50), p_telefono VARCHAR(15))
LANGUAGE plpgsql
AS $$
BEGIN
    insert into usuarios (
            id_login,
            id_departamento,
            nombre_usuario,
            apellido_usuario,
            telefono
        )
        values (
            p_id_login,
            p_id_departamento,
            p_nombre,
            p_apellido,
            p_telefono
        );
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminaradjunto(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from adjuntos
        where id_adjunto = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarasignacion(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from asignaciones
        where id_asignacion = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarcategoria(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from categorias
        where id_categoria = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarcomentario(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from comentarios
        where id_comentario = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminardepartamento(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from departamentos
        where id_departamento = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarhistorial(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from historialincidencias
        where id_historial = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarincidencia(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from incidencias
        where id_incidencia = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarlogin(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from login
        where id_login = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarprioridad(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from prioridades
        where id_prioridad = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarubicacion(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from ubicaciones
        where id_ubicacion = p_id;
END;
$$;

CREATE OR REPLACE PROCEDURE public.sp_eliminarusuario(p_id int)
LANGUAGE plpgsql
AS $$
BEGIN
    delete from usuarios
        where id_usuario = p_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.sp_listaradjuntos()
RETURNS TABLE (id_adjunto INTEGER, id_incidencia INTEGER, titulo_incidencia VARCHAR(100),
id_usuario INTEGER, usuario TEXT, nombre_archivo VARCHAR(100), ruta_archivo VARCHAR(255),
tipo_archivo VARCHAR(50), fecha_archivo TIMESTAMP)
LANGUAGE sql
AS $$
    select
            a.id_adjunto,
            a.id_incidencia,
            i.titulo_incidencia,
            a.id_usuario,
            concat(u.nombre_usuario, ' ', u.apellido_usuario) as usuario,
            a.nombre_archivo,
            a.ruta_archivo,
            a.tipo_archivo,
            a.fecha_archivo
        from adjuntos a
        inner join incidencias i
            on a.id_incidencia = i.id_incidencia
        inner join usuarios u
            on a.id_usuario = u.id_usuario
$$;

CREATE OR REPLACE FUNCTION public.sp_listarasignaciones()
RETURNS TABLE (id_asignacion INTEGER, id_incidencia INTEGER, id_usuario INTEGER, usuario TEXT,
titulo_incidencia VARCHAR(100), fecha_asignacion TIMESTAMP, fecha_finalizacion TIMESTAMP,
observaciones TEXT, estado_asignacion SMALLINT)
LANGUAGE sql
AS $$
    select
            a.id_asignacion,
            a.id_incidencia,
            a.id_usuario,
            concat(u.nombre_usuario, ' ', u.apellido_usuario) as usuario,
            i.titulo_incidencia,
            a.fecha_asignacion,
            a.fecha_finalizacion,
            a.observaciones,
            a.estado_asignacion
        from asignaciones a
        inner join usuarios u
            on a.id_usuario = u.id_usuario
        inner join incidencias i
            on a.id_incidencia = i.id_incidencia
$$;

CREATE OR REPLACE FUNCTION public.sp_listarcategorias()
RETURNS TABLE (id_categoria INTEGER, nombre_categoria VARCHAR(80), descripcion TEXT,
estado_categoria SMALLINT, nombre_departamento VARCHAR(80))
LANGUAGE sql
AS $$
    select
            c.id_categoria,
            c.nombre_categoria,
            c.descripcion,
            c.estado_categoria,
            d.nombre_departamento
        from categorias c
        inner join departamentos d
            on c.id_departamento = d.id_departamento
$$;

CREATE OR REPLACE FUNCTION public.sp_listarcomentarios()
RETURNS TABLE (id_comentario INTEGER, id_incidencia INTEGER, titulo_incidencia VARCHAR(100),
id_usuario INTEGER, usuario TEXT, comentario TEXT, fecha_comentario TIMESTAMP)
LANGUAGE sql
AS $$
    select
            c.id_comentario,
            c.id_incidencia,
            i.titulo_incidencia,
            c.id_usuario,
            concat(u.nombre_usuario, ' ', u.apellido_usuario) as usuario,
            c.comentario,
            c.fecha_comentario
        from comentarios c
        inner join incidencias i
            on c.id_incidencia = i.id_incidencia
        inner join usuarios u
            on c.id_usuario = u.id_usuario
$$;

CREATE OR REPLACE FUNCTION public.sp_listardepartamentos()
RETURNS TABLE (id_departamento INTEGER, nombre_departamento VARCHAR(80), descripcion TEXT,
estado_departamento SMALLINT)
LANGUAGE sql
AS $$
    select * from departamentos
$$;

CREATE OR REPLACE FUNCTION public.sp_listarhistorial()
RETURNS TABLE (id_historial INTEGER, id_incidencia INTEGER, titulo_incidencia VARCHAR(100),
id_usuario INTEGER, usuario TEXT, estado_anterior VARCHAR(30), estado_nuevo VARCHAR(30),
comentario TEXT, fecha_cambio TIMESTAMP)
LANGUAGE sql
AS $$
    select
            h.id_historial,
            h.id_incidencia,
            i.titulo_incidencia,
            h.id_usuario,
            concat(u.nombre_usuario, ' ', u.apellido_usuario) as usuario,
            h.estado_anterior,
            h.estado_nuevo,
            h.comentario,
            h.fecha_cambio
        from historialincidencias h
        inner join incidencias i
            on h.id_incidencia = i.id_incidencia
        inner join usuarios u
            on h.id_usuario = u.id_usuario
$$;

CREATE OR REPLACE FUNCTION public.sp_listarincidencias()
RETURNS TABLE (id_incidencia INTEGER, titulo_incidencia VARCHAR(100), descripcion_incidencia TEXT,
estado_incidencia VARCHAR(30), fecha_creacion TIMESTAMP, fecha_resolucion TIMESTAMP, usuario TEXT,
nombre_categoria VARCHAR(80), nombre_ubicacion VARCHAR(100), nombre_prioridad VARCHAR(20))
LANGUAGE sql
AS $$
    select
            i.id_incidencia,
            i.titulo_incidencia,
            i.descripcion_incidencia,
            i.estado_incidencia,
            i.fecha_creacion,
            i.fecha_resolucion,
            concat(u.nombre_usuario, ' ', u.apellido_usuario) as usuario,
            c.nombre_categoria,
            ub.nombre_ubicacion,
            p.nombre_prioridad
        from incidencias i
        inner join usuarios u
            on i.id_usuario = u.id_usuario
        inner join categorias c
            on i.id_categoria = c.id_categoria
        inner join ubicaciones ub
            on i.id_ubicacion = ub.id_ubicacion
        inner join prioridades p
            on i.id_prioridad = p.id_prioridad
$$;

CREATE OR REPLACE FUNCTION public.sp_listarlogin()
RETURNS TABLE (id_login INTEGER, correo_login VARCHAR(100), usuario_login VARCHAR(50),
contrasena_login VARCHAR(100), rol_login VARCHAR(30), estado_login SMALLINT)
LANGUAGE sql
AS $$
    select * from login
$$;

CREATE OR REPLACE FUNCTION public.sp_listarprioridades()
RETURNS TABLE (id_prioridad INTEGER, nombre_prioridad VARCHAR(20), descripcion TEXT,
estado_prioridad SMALLINT)
LANGUAGE sql
AS $$
    select * from prioridades
$$;

CREATE OR REPLACE FUNCTION public.sp_listarubicaciones()
RETURNS TABLE (id_ubicacion INTEGER, nombre_ubicacion VARCHAR(100), nivel VARCHAR(30),
descripcion TEXT, estado_ubicacion SMALLINT)
LANGUAGE sql
AS $$
    select * from ubicaciones
$$;

CREATE OR REPLACE FUNCTION public.sp_listarusuarios()
RETURNS TABLE (id_usuario INTEGER, nombre_usuario VARCHAR(50), apellido_usuario VARCHAR(50),
telefono VARCHAR(15), estado_usuario SMALLINT, usuario_login VARCHAR(50), correo_login VARCHAR(100),
rol_login VARCHAR(30), nombre_departamento VARCHAR(80))
LANGUAGE sql
AS $$
    select
            u.id_usuario,
            u.nombre_usuario,
            u.apellido_usuario,
            u.telefono,
            u.estado_usuario,
            l.usuario_login,
            l.correo_login,
            l.rol_login,
            d.nombre_departamento
        from usuarios u
        left join login l on u.id_login = l.id_login
        left join departamentos d on u.id_departamento = d.id_departamento
$$;