DROP TABLE IF EXISTS login CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS ubicaciones CASCADE;
DROP TABLE IF EXISTS prioridades CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS incidencias CASCADE;
DROP TABLE IF EXISTS asignaciones CASCADE;
DROP TABLE IF EXISTS comentarios CASCADE;
DROP TABLE IF EXISTS historialincidencias CASCADE;
DROP TABLE IF EXISTS adjuntos CASCADE;
DROP TABLE IF EXISTS notificaciones CASCADE;

CREATE TABLE login (
    id_login INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo_login VARCHAR(100) NOT NULL UNIQUE,
    usuario_login VARCHAR(50) NOT NULL UNIQUE,
    contrasena_login VARCHAR(100) NOT NULL,
    rol_login VARCHAR(30) NOT NULL CHECK (rol_login IN ('Administrador','Profesor','Personal TICS','Personal Servicios','Personal Infraestructura')),
    estado_login BOOLEAN DEFAULT TRUE
);

CREATE TABLE departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado_departamento BOOLEAN DEFAULT TRUE
);

CREATE TABLE ubicaciones (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ubicacion VARCHAR(100) NOT NULL,
    nivel VARCHAR(30),
    descripcion TEXT,
    estado_ubicacion BOOLEAN DEFAULT TRUE
);

CREATE TABLE prioridades (
    id_prioridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_prioridad VARCHAR(20) NOT NULL UNIQUE CHECK (nombre_prioridad IN ('Baja','Media','Alta','Critica')),
    descripcion TEXT,
    estado_prioridad BOOLEAN DEFAULT TRUE
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_login INTEGER,
    id_departamento INTEGER,
    nombre_usuario VARCHAR(50) NOT NULL,
    apellido_usuario VARCHAR(50) NOT NULL,
    telefono VARCHAR(15),
    estado_usuario BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_usuario_login FOREIGN KEY (id_login) REFERENCES login(id_login) ON DELETE SET NULL,
    CONSTRAINT fk_usuario_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE SET NULL
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL,
    nombre_categoria VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado_categoria BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_categoria_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE CASCADE
);

CREATE TABLE incidencias (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    id_prioridad INTEGER NOT NULL,
    titulo_incidencia VARCHAR(100) NOT NULL,
    descripcion_incidencia TEXT NOT NULL,
    estado_incidencia VARCHAR(30) DEFAULT 'Pendiente' CHECK (estado_incidencia IN ('Pendiente','En Revision','En Proceso','Resuelto','Cerrado')),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_resolucion TIMESTAMP,
    CONSTRAINT fk_incidencia_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones(id_ubicacion) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_prioridad FOREIGN KEY (id_prioridad) REFERENCES prioridades(id_prioridad) ON DELETE CASCADE
);

CREATE TABLE asignaciones (
    id_asignacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMP,
    observaciones TEXT,
    estado_asignacion BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_asignacion_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_asignacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    comentario TEXT NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentario_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE historialincidencias (
    id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo VARCHAR(30) NOT NULL,
    comentario TEXT,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historial_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE adjuntos (
    id_adjunto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    nombre_archivo VARCHAR(100) NOT NULL,
    ruta_archivo VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(50),
    fecha_archivo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adjunto_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_adjunto_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE notificaciones (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_incidencia INTEGER,
    mensaje VARCHAR(255) NOT NULL,
    leida BOOLEAN DEFAULT FALSE,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_notificacion_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE
);

-- Datos de login
INSERT INTO login VALUES (1,'admin.general@cartagena.edu','admin_gral','pass1234','Administrador',TRUE),(2,'tics.soporte1@cartagena.edu','tics_juan','pass1234','Personal TICS',TRUE),(3,'tics.soporte2@cartagena.edu','tics_maria','pass1234','Personal TICS',TRUE),(4,'prof.matematicas@cartagena.edu','prof_carlos','pass1234','Profesor',TRUE),(5,'prof.historia@cartagena.edu','prof_ana','pass1234','Profesor',TRUE),(6,'servicios.limpieza@cartagena.edu','serv_pedro','pass1234','Personal Servicios',TRUE),(7,'servicios.mantenimiento@cartagena.edu','serv_luisa','pass1234','Personal Servicios',TRUE),(8,'infra.redes@cartagena.edu','infra_jorge','pass1234','Personal Infraestructura',TRUE),(9,'prof.ciencias@cartagena.edu','prof_sofia','pass1234','Profesor',TRUE),(10,'infra.seguridad@cartagena.edu','infra_carmen','pass1234','Personal Infraestructura',TRUE);

-- Datos de departamentos
INSERT INTO departamentos VALUES (1,'Dirección General','Departamento administrativo y de dirección superior',TRUE),(2,'Soporte TICS','Soporte técnico, equipos de cómputo y software institucional',TRUE),(3,'Infraestructura y Redes','Mantenimiento de redes, cableado y servidores',TRUE),(4,'Servicios Generales','Limpieza, conserjería y áreas comunes',TRUE),(5,'Académico - Matemáticas','Departamento de enseñanza de matemáticas y física',TRUE),(6,'Académico - Ciencias','Laboratorios y materias científicas',TRUE),(7,'Académico - Humanidades','Historia, literatura y ciencias sociales',TRUE),(8,'Mantenimiento Fiduciario','Reparaciones locativas, plomería y electricidad',TRUE),(9,'Recursos Humanos','Gestión de personal docente y administrativo',TRUE),(10,'Biblioteca','Gestión de libros, salas de lectura y recursos digitales',TRUE);

-- Datos de ubicaciones
INSERT INTO ubicaciones VALUES (1,'Salón H1 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(2,'Salón H2 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(3,'Salón H3 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(4,'Salón H4 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(5,'Salón H5 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(6,'Salón H6 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(7,'Salón H7 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(8,'Salón H8 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(9,'Salón H9 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(10,'Salón H10 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(11,'Salón H11 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(12,'Salón H12 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(13,'Salón H13 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(14,'Salón H14 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(15,'Salón H15 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(16,'Salón H16 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(17,'Salón H17 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(18,'Salón H18 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(19,'Salón H19 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(20,'Salón H20 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(21,'Salón H21 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(22,'Salón H22 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(23,'Salón H23 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(24,'Salón H24 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(25,'Salón H25 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(26,'Salón H26 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(27,'Salón H27 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(28,'Salón H28 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(29,'Salón H29 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(30,'Salón H30 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(31,'Salón H31 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(32,'Laboratorio de Computación - H32 (Edificio de Básicos)','Edificio de Básicos','Laboratorio de computación',TRUE),(33,'Salón H33 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(34,'Salón H34 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(35,'Salón H35 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(36,'Salón H36 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(37,'Salón H37 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(38,'Salón H38 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(39,'Salón H39 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(40,'Salón H40 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(41,'Salón H41 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(42,'Salón H42 (Edificio de Básicos)','Edificio de Básicos','Salón de clases',TRUE),(43,'Salón C1 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(44,'Laboratorio de Computación - C2 (Edificio de Diversificado)','Edificio de Diversificado','Laboratorio de computación',TRUE),(45,'Salón C3 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(46,'Salón C4 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(47,'Salón C5 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(48,'Salón C6 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(49,'Salón C7 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(50,'Salón C8 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(51,'Salón C9 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(52,'Salón C10 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(53,'Salón C11 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(54,'Salón C12 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(55,'Salón C13 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(56,'Salón C14 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(57,'Salón C15 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(58,'Salón C16 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(59,'Salón C17 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(60,'Salón C18 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(61,'Salón C19 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(62,'Salón C20 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(63,'Salón C21 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(64,'Salón C22 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(65,'Salón C23 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(66,'Salón C24 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(67,'Salón C25 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(68,'Salón C26 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(69,'Laboratorio de Computación - C27 (Edificio de Diversificado)','Edificio de Diversificado','Laboratorio de computación',TRUE),(70,'Laboratorio de Computación - C28 (Edificio de Diversificado)','Edificio de Diversificado','Laboratorio de computación',TRUE),(71,'Salón C29 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(72,'Salón C30 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(73,'Salón C31 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(74,'Salón C32 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(75,'Salón C33 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(76,'Salón C34 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(77,'Salón C35 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(78,'Salón C36 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(79,'Salón C37 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(80,'Salón C38 (Edificio de Diversificado)','Edificio de Diversificado','Salón de clases',TRUE),(81,'Laboratorio de Computación - G12',NULL,'Laboratorio de computación',TRUE),(82,'Laboratorio de Computación - B2',NULL,'Laboratorio de computación',TRUE),(83,'Cafetería',NULL,'Área de comidas y descanso',TRUE),(84,'Cancha Sintética',NULL,'Área deportiva de uso institucional',TRUE),(85,'Salones de Preceptoría',NULL,'Áreas de tutoría y seguimiento académico',TRUE),(86,'Talleres de Mecánica',NULL,'Talleres de práctica técnica',TRUE),(87,'Patio',NULL,'Área común al aire libre',TRUE),(88,'Auditorio de Básicos',NULL,'Auditorio del edificio de Básicos',TRUE),(89,'Auditorio de Diversificado',NULL,'Auditorio del edificio de Diversificado',TRUE);

-- Datos de prioridades
INSERT INTO prioridades VALUES (1,'Baja','Incidencias menores que no afectan la operatividad inmediata',TRUE),(2,'Media','Incidencias que afectan parcialmente las labores cotidianas',TRUE),(3,'Alta','Problemas urgentes que detienen una actividad importante',TRUE),(4,'Critica','Emergencias absolutas que paralizan áreas completas o sistemas',TRUE);

-- Datos de usuarios
INSERT INTO usuarios VALUES (1,1,1,'Roberto','Mendoza','5551-0101',TRUE),(2,2,2,'Juan','Pérez','5551-0202',TRUE),(3,3,2,'María','Gómez','5551-0303',TRUE),(4,4,5,'Carlos','López','5551-0404',TRUE),(5,5,7,'Ana','Martínez','5551-0505',TRUE),(6,6,4,'Pedro','Sánchez','5551-0606',TRUE),(7,7,8,'Luisa','Fernández','5551-0707',TRUE),(8,8,3,'Jorge','Ramírez','5551-0808',TRUE),(9,9,6,'Sofía','Castillo','5551-0909',TRUE),(10,10,8,'Carmen','Morales','5551-1010',TRUE);

-- Datos de categorias
INSERT INTO categorias VALUES (1,2,'Fallos de Hardware','Problemas con computadoras, pantallas o proyectores',TRUE),(2,2,'Problemas de Software','Errores en sistemas operativos o aplicaciones institucionales',TRUE),(3,3,'Conectividad Wi-Fi','Fallas en la señal inalámbrica del campus',TRUE),(4,3,'Cables de Red','Puntos de red dañados o sin conexión física',TRUE),(5,4,'Limpieza de Aula','Solicitud de limpieza en salones específicos',TRUE),(6,8,'Iluminación','Bombillas fundidas o problemas con interruptores',TRUE),(7,8,'Plomería y Fugas','Problemas en tuberías, baños o bebederos',TRUE),(8,5,'Material Didáctico','Falta de recursos en aulas de matemáticas',TRUE),(9,6,'Equipos de Laboratorio','Mal funcionamiento de microscopios o instrumentos',TRUE);

-- Datos de incidencias
INSERT INTO incidencias VALUES (1,4,1,1,2,'Proyector sin video','El proyector del aula 101 no enciende al conectar la laptop','Pendiente','2026-09-08 19:38:02',NULL),(2,5,2,2,3,'Error en plataforma virtual','No carga el módulo de calificaciones para el curso de historia','Pendiente','2026-09-08 19:38:02',NULL),(3,4,3,3,2,'Sin señal de Wi-Fi en lab','Los equipos de computación no detectan la red institucional','Pendiente','2026-09-08 19:38:02',NULL),(4,6,5,9,1,'Basura acumulada en cafetería','Se requiere recolección urgente de residuos en mesas exteriores','Pendiente','2026-09-08 19:38:02',NULL),(5,7,6,7,2,'Lámpara fundida','La iluminación del salón de profesores parpadea constantemente','Pendiente','2026-09-08 19:38:02',NULL),(6,8,4,10,4,'Caída del servidor principal','Inaccesibilidad total a los sistemas de red y carpetas compartidas','Pendiente','2026-09-08 19:38:02',NULL),(7,9,9,4,3,'Microscopio dañado','El lente del microscopio número 4 está rayado','Pendiente','2026-09-08 19:38:02',NULL),(8,4,8,1,1,'Pintura descascarada','Se observa daño estético en la pared lateral del aula 101','Pendiente','2026-09-08 19:38:02',NULL),(9,5,7,5,3,'Fuga de agua en baños','Grifo roto en el baño principal de la biblioteca','Pendiente','2026-09-08 19:38:02',NULL);

-- Datos de asignaciones
INSERT INTO asignaciones VALUES (1,1,2,'2026-09-08 19:38:02',NULL,'Asignado a revisión técnica de proyector',TRUE),(2,2,3,'2026-09-08 19:38:02',NULL,'Revisión de base de datos y credenciales de usuario',TRUE),(3,3,8,'2026-09-08 19:38:02',NULL,'Inspección del Access Point del edificio B',TRUE),(4,4,6,'2026-09-08 19:38:02',NULL,'Turno de limpieza asignado al personal de servicio',TRUE),(5,5,7,'2026-09-08 19:38:02',NULL,'Cambio de balastro y bombilla programado',TRUE),(6,6,8,'2026-09-08 19:38:02',NULL,'Atención inmediata por caída de servidores',TRUE),(7,7,3,'2026-09-08 19:38:02',NULL,'Revisión de equipo especializado de laboratorio',TRUE),(8,8,7,'2026-09-08 19:38:02',NULL,'Evaluación de daños estéticos',TRUE),(9,9,7,'2026-09-08 19:38:02',NULL,'Reparación de tubería y grifería',TRUE);

-- Datos de comentarios
INSERT INTO comentarios VALUES (1,1,4,'El cable VGA ya fue probado pero el puerto no responde.','2026-09-08 19:38:02'),(2,2,5,'Aún no puedo acceder con mi usuario institucional.','2026-09-08 19:38:02'),(3,3,2,'El punto de red ya da enlace intermitente.','2026-09-08 19:38:02'),(4,4,6,'Área limpia y despejada.','2026-09-08 19:38:02'),(5,5,7,'La iluminación quedó funcionando correctamente.','2026-09-08 19:38:02'),(6,6,8,'Servicios restaurados al 100%.','2026-09-08 19:38:02'),(7,7,9,'Se necesita cotizar repuesto con proveedor externo.','2026-09-08 19:38:02'),(8,8,4,'Esperando aprobación para iniciar trabajos de pintura.','2026-09-08 19:38:02'),(9,9,7,'Fuga controlada exitosamente.','2026-09-08 19:38:02');

-- Datos de historialincidencias
INSERT INTO historialincidencias VALUES (1,1,2,'Pendiente','En Revision','Se recibe la incidencia y se verifica el equipo.','2026-09-08 19:38:02'),(2,2,3,'Pendiente','En Proceso','Se contacta al proveedor del software.','2026-09-08 19:38:02'),(3,3,8,'Pendiente','En Revision','Verificando estado del router principal.','2026-09-08 19:38:02'),(4,4,6,'Pendiente','En Proceso','Personal de limpieza enviado al área.','2026-09-08 19:38:02'),(5,5,7,'Pendiente','Resuelto','Lámpara sustituida con éxito.','2026-09-08 19:38:02'),(6,6,8,'Pendiente','En Proceso','Reinicio forzoso de servidores y respaldo.','2026-09-08 19:38:02'),(7,7,3,'Pendiente','En Revision','Revisando inventario de repuestos.','2026-09-08 19:38:02'),(8,8,7,'Pendiente','Pendiente','A la espera de presupuesto para pintura.','2026-09-08 19:38:02'),(9,9,7,'Pendiente','En Proceso','Cerrada llave de paso principal para reparación.','2026-09-08 19:38:02');

-- Datos de adjuntos
INSERT INTO adjuntos VALUES (1,1,4,'error_proyector.png','/uploads/incidencias/error_proyector.png','image/png','2026-09-08 19:38:02'),(2,2,5,'captura_error_login.jpg','/uploads/incidencias/captura_error_login.jpg','image/jpeg','2026-09-08 19:38:02'),(3,3,4,'test_ping.log','/uploads/incidencias/test_ping.log','text/plain','2026-09-08 19:38:02'),(4,4,6,'estado_cafeteria.jpg','/uploads/incidencias/estado_cafeteria.jpg','image/jpeg','2026-09-08 19:38:02'),(5,5,7,'lampara_rota.jpg','/uploads/incidencias/lampara_rota.jpg','image/jpeg','2026-09-08 19:38:02'),(6,6,8,'log_servidor.txt','/uploads/incidencias/log_servidor.txt','text/plain','2026-09-08 19:38:02'),(7,7,9,'microscopio_daño.png','/uploads/incidencias/microscopio_dano.png','image/png','2026-09-08 19:38:02'),(8,8,4,'pared_aula101.jpg','/uploads/incidencias/pared_aula101.jpg','image/jpeg','2026-09-08 19:38:02'),(9,9,7,'fuga_bano.mp4','/uploads/incidencias/fuga_bano.mp4','video/mp4','2026-09-08 19:38:02');

SELECT setval(pg_get_serial_sequence('login', 'id_login'), COALESCE((SELECT MAX(id_login) FROM login), 1), true);
SELECT setval(pg_get_serial_sequence('departamentos', 'id_departamento'), COALESCE((SELECT MAX(id_departamento) FROM departamentos), 1), true);
SELECT setval(pg_get_serial_sequence('ubicaciones', 'id_ubicacion'), COALESCE((SELECT MAX(id_ubicacion) FROM ubicaciones), 1), true);
SELECT setval(pg_get_serial_sequence('prioridades', 'id_prioridad'), COALESCE((SELECT MAX(id_prioridad) FROM prioridades), 1), true);
SELECT setval(pg_get_serial_sequence('usuarios', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM usuarios), 1), true);
SELECT setval(pg_get_serial_sequence('categorias', 'id_categoria'), COALESCE((SELECT MAX(id_categoria) FROM categorias), 1), true);
SELECT setval(pg_get_serial_sequence('incidencias', 'id_incidencia'), COALESCE((SELECT MAX(id_incidencia) FROM incidencias), 1), true);
SELECT setval(pg_get_serial_sequence('asignaciones', 'id_asignacion'), COALESCE((SELECT MAX(id_asignacion) FROM asignaciones), 1), true);
SELECT setval(pg_get_serial_sequence('comentarios', 'id_comentario'), COALESCE((SELECT MAX(id_comentario) FROM comentarios), 1), true);
SELECT setval(pg_get_serial_sequence('historialincidencias', 'id_historial'), COALESCE((SELECT MAX(id_historial) FROM historialincidencias), 1), true);
SELECT setval(pg_get_serial_sequence('adjuntos', 'id_adjunto'), COALESCE((SELECT MAX(id_adjunto) FROM adjuntos), 1), true);