DROP TABLE IF EXISTS login CASCADE;
DROP TABLE IF EXISTS departamentos CASCADE;
DROP TABLE IF EXISTS ubicaciones CASCADE;
DROP TABLE IF EXISTS prioridades CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS incidencias CASCADE;
DROP TABLE IF EXISTS asignaciones CASCADE;
DROP TABLE IF EXISTS comentarios CASCADE;
DROP TABLE IF EXISTS historialincidencias CASCADE;
DROP TABLE IF EXISTS adjuntos CASCADE;

CREATE TABLE login (
    id_login INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    correo_login VARCHAR(100) NOT NULL UNIQUE,
    usuario_login VARCHAR(50) NOT NULL UNIQUE,
    contrasena_login VARCHAR(100) NOT NULL,
    rol_login VARCHAR(30) NOT NULL CHECK (rol_login IN ('Administrador','Profesor','Personal TICS','Personal Servicios','Personal Infraestructura')),
    estado_login BOOLEAN DEFAULT TRUE
);

CREATE TABLE departamentos (
    id_departamento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_departamento VARCHAR(80) NOT NULL UNIQUE,
    descripcion TEXT,
    estado_departamento BOOLEAN DEFAULT TRUE
);

CREATE TABLE ubicaciones (
    id_ubicacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ubicacion VARCHAR(100) NOT NULL,
    nivel VARCHAR(30),
    descripcion TEXT,
    estado_ubicacion BOOLEAN DEFAULT TRUE
);

CREATE TABLE prioridades (
    id_prioridad INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_prioridad VARCHAR(20) NOT NULL UNIQUE CHECK (nombre_prioridad IN ('Baja','Media','Alta','Critica')),
    descripcion TEXT,
    estado_prioridad BOOLEAN DEFAULT TRUE
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_login INTEGER,
    id_departamento INTEGER,
    nombre_usuario VARCHAR(50) NOT NULL,
    apellido_usuario VARCHAR(50) NOT NULL,
    telefono VARCHAR(15),
    estado_usuario BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_usuario_login FOREIGN KEY (id_login) REFERENCES login(id_login) ON DELETE SET NULL,
    CONSTRAINT fk_usuario_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE SET NULL
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_departamento INTEGER NOT NULL,
    nombre_categoria VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado_categoria BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_categoria_departamento FOREIGN KEY (id_departamento) REFERENCES departamentos(id_departamento) ON DELETE CASCADE
);

CREATE TABLE incidencias (
    id_incidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_categoria INTEGER NOT NULL,
    id_ubicacion INTEGER NOT NULL,
    id_prioridad INTEGER NOT NULL,
    titulo_incidencia VARCHAR(100) NOT NULL,
    descripcion_incidencia TEXT NOT NULL,
    estado_incidencia VARCHAR(30) DEFAULT 'Pendiente' CHECK (estado_incidencia IN ('Pendiente','En Revision','En Proceso','Resuelto','Cerrado')),
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_resolucion TIMESTAMP,
    CONSTRAINT fk_incidencia_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_categoria FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_ubicacion FOREIGN KEY (id_ubicacion) REFERENCES ubicaciones(id_ubicacion) ON DELETE CASCADE,
    CONSTRAINT fk_incidencia_prioridad FOREIGN KEY (id_prioridad) REFERENCES prioridades(id_prioridad) ON DELETE CASCADE
);

CREATE TABLE asignaciones (
    id_asignacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_asignacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fecha_finalizacion TIMESTAMP,
    observaciones TEXT,
    estado_asignacion BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_asignacion_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_asignacion_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE comentarios (
    id_comentario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    comentario TEXT NOT NULL,
    fecha_comentario TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comentario_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_comentario_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE historialincidencias (
    id_historial INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    estado_anterior VARCHAR(30),
    estado_nuevo VARCHAR(30) NOT NULL,
    comentario TEXT,
    fecha_cambio TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_historial_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_historial_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

CREATE TABLE adjuntos (
    id_adjunto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_incidencia INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    nombre_archivo VARCHAR(100) NOT NULL,
    ruta_archivo VARCHAR(255) NOT NULL,
    tipo_archivo VARCHAR(50),
    fecha_archivo TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_adjunto_incidencia FOREIGN KEY (id_incidencia) REFERENCES incidencias(id_incidencia) ON DELETE CASCADE,
    CONSTRAINT fk_adjunto_usuario FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario) ON DELETE CASCADE
);

-- Datos de login
INSERT INTO login VALUES (1,'admin.general@cartagena.edu','admin_gral','pass1234','Administrador',TRUE),(2,'tics.soporte1@cartagena.edu','tics_juan','pass1234','Personal TICS',TRUE),(3,'tics.soporte2@cartagena.edu','tics_maria','pass1234','Personal TICS',TRUE),(4,'prof.matematicas@cartagena.edu','prof_carlos','pass1234','Profesor',TRUE),(5,'prof.historia@cartagena.edu','prof_ana','pass1234','Profesor',TRUE),(6,'servicios.limpieza@cartagena.edu','serv_pedro','pass1234','Personal Servicios',TRUE),(7,'servicios.mantenimiento@cartagena.edu','serv_luisa','pass1234','Personal Servicios',TRUE),(8,'infra.redes@cartagena.edu','infra_jorge','pass1234','Personal Infraestructura',TRUE),(9,'prof.ciencias@cartagena.edu','prof_sofia','pass1234','Profesor',TRUE),(10,'infra.seguridad@cartagena.edu','infra_carmen','pass1234','Personal Infraestructura',TRUE);

-- Datos de departamentos
INSERT INTO departamentos VALUES (1,'Dirección General','Departamento administrativo y de dirección superior',TRUE),(2,'Soporte TICS','Soporte técnico, equipos de cómputo y software institucional',TRUE),(3,'Infraestructura y Redes','Mantenimiento de redes, cableado y servidores',TRUE),(4,'Servicios Generales','Limpieza, conserjería y áreas comunes',TRUE),(5,'Académico - Matemáticas','Departamento de enseñanza de matemáticas y física',TRUE),(6,'Académico - Ciencias','Laboratorios y materias científicas',TRUE),(7,'Académico - Humanidades','Historia, literatura y ciencias sociales',TRUE),(8,'Mantenimiento Fiduciario','Reparaciones locativas, plomería y electricidad',TRUE),(9,'Recursos Humanos','Gestión de personal docente y administrativo',TRUE),(10,'Biblioteca','Gestión de libros, salas de lectura y recursos digitales',TRUE);

-- Datos de ubicaciones
INSERT INTO ubicaciones VALUES (1,'Edificio A - Aula 101','Nivel 1','Salón de clases principal planta baja',TRUE),(2,'Edificio A - Aula 202','Nivel 2','Salón de clases planta alta',TRUE),(3,'Edificio B - Laboratorio de Computación','Nivel 1','Sala de equipos y prácticas TICS',TRUE),(4,'Edificio B - Laboratorio de Ciencias','Nivel 2','Laboratorio de física y química',TRUE),(5,'Biblioteca Central','Nivel 1','Área de lectura y estanterías',TRUE),(6,'Oficinas Administrativas','Nivel 1','Dirección y secretaría general',TRUE),(7,'Salón de Profesores','Nivel 2','Área de descanso y planeación docente',TRUE),(8,'Área Deportiva - Gimnasio','Nivel 1','Gimnasio techado institucional',TRUE),(9,'Cafetería Estudiantil','Nivel 1','Área de comidas y descanso',TRUE),(10,'Centro de Servidores (DataCenter)','Nivel 1','Cuarto técnico de redes principal',TRUE);

-- Datos de prioridades
INSERT INTO prioridades VALUES (1,'Baja','Incidencias menores que no afectan la operatividad inmediata',TRUE),(2,'Media','Incidencias que afectan parcialmente las labores cotidianas',TRUE),(3,'Alta','Problemas urgentes que detienen una actividad importante',TRUE),(4,'Critica','Emergencias absolutas que paralizan áreas completas o sistemas',TRUE);

-- Datos de usuarios
INSERT INTO usuarios VALUES (1,1,1,'Roberto','Mendoza','5551-0101',TRUE),(2,2,2,'Juan','Pérez','5551-0202',TRUE),(3,3,2,'María','Gómez','5551-0303',TRUE),(4,4,5,'Carlos','López','5551-0404',TRUE),(5,5,7,'Ana','Martínez','5551-0505',TRUE),(6,6,4,'Pedro','Sánchez','5551-0606',TRUE),(7,7,8,'Luisa','Fernández','5551-0707',TRUE),(8,8,3,'Jorge','Ramírez','5551-0808',TRUE),(9,9,6,'Sofía','Castillo','5551-0909',TRUE),(10,10,8,'Carmen','Morales','5551-1010',TRUE);

-- Datos de categorias
INSERT INTO categorias VALUES (1,2,'Fallos de Hardware','Problemas con computadoras, pantallas o proyectores',TRUE),(2,2,'Problemas de Software','Errores en sistemas operativos o aplicaciones institucionales',TRUE),(3,3,'Conectividad Wi-Fi','Fallas en la señal inalámbrica del campus',TRUE),(4,3,'Cables de Red','Puntos de red dañados o sin conexión física',TRUE),(5,4,'Limpieza de Aula','Solicitud de limpieza en salones específicos',TRUE),(6,8,'Iluminación','Bombillas fundidas o problemas con interruptores',TRUE),(7,8,'Plomería y Fugas','Problemas en tuberías, baños o bebederos',TRUE),(8,5,'Material Didáctico','Falta de recursos en aulas de matemáticas',TRUE),(9,6,'Equipos de Laboratorio','Mal funcionamiento de microscopios o instrumentos',TRUE),(10,10,'Préstamo de Libros','Incidencias con el catálogo o sistema de biblioteca',TRUE);

-- Datos de incidencias
INSERT INTO incidencias VALUES (1,4,1,1,2,'Proyector sin video','El proyector del aula 101 no enciende al conectar la laptop','Pendiente','2026-09-08 19:38:02',NULL),(2,5,2,2,3,'Error en plataforma virtual','No carga el módulo de calificaciones para el curso de historia','Pendiente','2026-09-08 19:38:02',NULL),(3,4,3,3,2,'Sin señal de Wi-Fi en lab','Los equipos de computación no detectan la red institucional','Pendiente','2026-09-08 19:38:02',NULL),(4,6,5,9,1,'Basura acumulada en cafetería','Se requiere recolección urgente de residuos en mesas exteriores','Pendiente','2026-09-08 19:38:02',NULL),(5,7,6,7,2,'Lámpara fundida','La iluminación del salón de profesores parpadea constantemente','Pendiente','2026-09-08 19:38:02',NULL),(6,8,4,10,4,'Caída del servidor principal','Inaccesibilidad total a los sistemas de red y carpetas compartidas','Pendiente','2026-09-08 19:38:02',NULL),(7,9,9,4,3,'Microscopio dañado','El lente del microscopio número 4 está rayado','Pendiente','2026-09-08 19:38:02',NULL),(8,4,8,1,1,'Pintura descascarada','Se observa daño estético en la pared lateral del aula 101','Pendiente','2026-09-08 19:38:02',NULL),(9,5,7,5,3,'Fuga de agua en baños','Grifo roto en el baño principal de la biblioteca','Pendiente','2026-09-08 19:38:02',NULL),(10,10,10,5,2,'Sistema de biblioteca lento','El software de búsqueda de libros presenta retrasos','Pendiente','2026-09-08 19:38:02',NULL);

-- Datos de asignaciones
INSERT INTO asignaciones VALUES (1,1,2,'2026-09-08 19:38:02',NULL,'Asignado a revisión técnica de proyector',TRUE),(2,2,3,'2026-09-08 19:38:02',NULL,'Revisión de base de datos y credenciales de usuario',TRUE),(3,3,8,'2026-09-08 19:38:02',NULL,'Inspección del Access Point del edificio B',TRUE),(4,4,6,'2026-09-08 19:38:02',NULL,'Turno de limpieza asignado al personal de servicio',TRUE),(5,5,7,'2026-09-08 19:38:02',NULL,'Cambio de balastro y bombilla programado',TRUE),(6,6,8,'2026-09-08 19:38:02',NULL,'Atención inmediata por caída de servidores',TRUE),(7,7,3,'2026-09-08 19:38:02',NULL,'Revisión de equipo especializado de laboratorio',TRUE),(8,8,7,'2026-09-08 19:38:02',NULL,'Evaluación de daños estéticos',TRUE),(9,9,7,'2026-09-08 19:38:02',NULL,'Reparación de tubería y grifería',TRUE),(10,10,2,'2026-09-08 19:38:02',NULL,'Optimización de base de datos bibliotecaria',TRUE);

-- Datos de comentarios
INSERT INTO comentarios VALUES (1,1,4,'El cable VGA ya fue probado pero el puerto no responde.','2026-09-08 19:38:02'),(2,2,5,'Aún no puedo acceder con mi usuario institucional.','2026-09-08 19:38:02'),(3,3,2,'El punto de red ya da enlace intermitente.','2026-09-08 19:38:02'),(4,4,6,'Área limpia y despejada.','2026-09-08 19:38:02'),(5,5,7,'La iluminación quedó funcionando correctamente.','2026-09-08 19:38:02'),(6,6,8,'Servicios restaurados al 100%.','2026-09-08 19:38:02'),(7,7,9,'Se necesita cotizar repuesto con proveedor externo.','2026-09-08 19:38:02'),(8,8,4,'Esperando aprobación para iniciar trabajos de pintura.','2026-09-08 19:38:02'),(9,9,7,'Fuga controlada exitosamente.','2026-09-08 19:38:02'),(10,10,10,'El sistema responde mucho más rápido ahora.','2026-09-08 19:38:02');

-- Datos de historialincidencias
INSERT INTO historialincidencias VALUES (1,1,2,'Pendiente','En Revision','Se recibe la incidencia y se verifica el equipo.','2026-09-08 19:38:02'),(2,2,3,'Pendiente','En Proceso','Se contacta al proveedor del software.','2026-09-08 19:38:02'),(3,3,8,'Pendiente','En Revision','Verificando estado del router principal.','2026-09-08 19:38:02'),(4,4,6,'Pendiente','En Proceso','Personal de limpieza enviado al área.','2026-09-08 19:38:02'),(5,5,7,'Pendiente','Resuelto','Lámpara sustituida con éxito.','2026-09-08 19:38:02'),(6,6,8,'Pendiente','En Proceso','Reinicio forzoso de servidores y respaldo.','2026-09-08 19:38:02'),(7,7,3,'Pendiente','En Revision','Revisando inventario de repuestos.','2026-09-08 19:38:02'),(8,8,7,'Pendiente','Pendiente','A la espera de presupuesto para pintura.','2026-09-08 19:38:02'),(9,9,7,'Pendiente','En Proceso','Cerrada llave de paso principal para reparación.','2026-09-08 19:38:02'),(10,10,2,'Pendiente','Resuelto','Servidor de biblioteca optimizado.','2026-09-08 19:38:02');

-- Datos de adjuntos
INSERT INTO adjuntos VALUES (1,1,4,'error_proyector.png','/uploads/incidencias/error_proyector.png','image/png','2026-09-08 19:38:02'),(2,2,5,'captura_error_login.jpg','/uploads/incidencias/captura_error_login.jpg','image/jpeg','2026-09-08 19:38:02'),(3,3,4,'test_ping.log','/uploads/incidencias/test_ping.log','text/plain','2026-09-08 19:38:02'),(4,4,6,'estado_cafeteria.jpg','/uploads/incidencias/estado_cafeteria.jpg','image/jpeg','2026-09-08 19:38:02'),(5,5,7,'lampara_rota.jpg','/uploads/incidencias/lampara_rota.jpg','image/jpeg','2026-09-08 19:38:02'),(6,6,8,'log_servidor.txt','/uploads/incidencias/log_servidor.txt','text/plain','2026-09-08 19:38:02'),(7,7,9,'microscopio_daño.png','/uploads/incidencias/microscopio_dano.png','image/png','2026-09-08 19:38:02'),(8,8,4,'pared_aula101.jpg','/uploads/incidencias/pared_aula101.jpg','image/jpeg','2026-09-08 19:38:02'),(9,9,7,'fuga_bano.mp4','/uploads/incidencias/fuga_bano.mp4','video/mp4','2026-09-08 19:38:02'),(10,10,10,'reporte_rendimiento.pdf','/uploads/incidencias/reporte_rendimiento.pdf','application/pdf','2026-09-08 19:38:02');

SELECT setval(pg_get_serial_sequence('login', 'id_login'), COALESCE((SELECT MAX(id_login) FROM login), 1), true);
SELECT setval(pg_get_serial_sequence('departamentos', 'id_departamento'), COALESCE((SELECT MAX(id_departamento) FROM departamentos), 1), true);
SELECT setval(pg_get_serial_sequence('ubicaciones', 'id_ubicacion'), COALESCE((SELECT MAX(id_ubicacion) FROM ubicaciones), 1), true);
SELECT setval(pg_get_serial_sequence('prioridades', 'id_prioridad'), COALESCE((SELECT MAX(id_prioridad) FROM prioridades), 1), true);
SELECT setval(pg_get_serial_sequence('usuarios', 'id_usuario'), COALESCE((SELECT MAX(id_usuario) FROM usuarios), 1), true);
SELECT setval(pg_get_serial_sequence('categorias', 'id_categoria'), COALESCE((SELECT MAX(id_categoria) FROM categorias), 1), true);
SELECT setval(pg_get_serial_sequence('incidencias', 'id_incidencia'), COALESCE((SELECT MAX(id_incidencia) FROM incidencias), 1), true);
SELECT setval(pg_get_serial_sequence('asignaciones', 'id_asignacion'), COALESCE((SELECT MAX(id_asignacion) FROM asignaciones), 1), true);
SELECT setval(pg_get_serial_sequence('comentarios', 'id_comentario'), COALESCE((SELECT MAX(id_comentario) FROM comentarios), 1), true);
SELECT setval(pg_get_serial_sequence('historialincidencias', 'id_historial'), COALESCE((SELECT MAX(id_historial) FROM historialincidencias), 1), true);
SELECT setval(pg_get_serial_sequence('adjuntos', 'id_adjunto'), COALESCE((SELECT MAX(id_adjunto) FROM adjuntos), 1), true);